# App-wide configurations for Chef (http://railscasts.com/episodes/85)
# Plus a trick to make generalize configs (http://code.google.com/p/rails-appconfig-generator/)

development: &general_settings 
  perform_authentication: true
  username: cmutv
  password: foo
  order_notification_from_address: 'creditcard_info@cmu.edu'

test: 
  <<: *general_settings 

production:
  <<: *general_settings 