development: &general_settings 
  :server: "imap.gmail.com"
  :type: "imap"
  :ssl: true
  :use_login: true
  :port: 993
  :username: "store@cmutv.org"
  :password: "foo"
  :processed_folder: "Chef - Fetched"
  :error_folder: "INBOX"
  :receiver: "OrderMailer"
  
test:
  <<: *general_settings 
  
production:
  <<: *general_settings 
  